on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    #env:
    #  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: Setup R
      #  uses: r-lib/actions/setup-r@v1

      #- uses: r-lib/actions/setup-renv@v2
      #- name: preload
      #  run: R -e 'source("cache.R")' || true

# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        run: Rscript run_beetles_baselines.R 
